name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements3.txt
      - name: Run Tests
        run: python3 -m unittest discover -s ./tests -p "test_*.py"
